name: Divinitas Blog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39162
title: Random thoughts from our corner of the industry...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58585a'
    - '#949599'
    - '#f37b20'
    - '#f6c193'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
