name: Divinitas Blog
favicon: null
layout_spectrum: 0.25227
typography_spectrum: 0.39162
title: Divinitas - Random thoughts from our corner of the industry...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58585a'
    - '#949599'
    - '#f57722'
    - '#cacacb'
  brandStrength: 0.125
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
