name: Divinitas
favicon: null
layout_spectrum: 0.37892
typography_spectrum: 0.39162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58585a'
    - '#949599'
    - '#f37b20'
    - '#f6c193'
  brandStrength: 0.5
  lightness: 0.9708953395020217
  saturation: 0.1004396912176162
  rhythmicContrast: 0.4893156071193516
purpose: []
